name: On push main

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and deploy to production

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: NPM cache
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set TZ
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'America/Sao_Paulo'

      - name: Setup Test Dependencies
        run: docker-compose up -d

      - name: Tests
        run: npm test

      - name: Retrieve version
        run: echo "RELEASE=$(cat package.json|jq -r '.version')" >> $GITHUB_ENV

      - name: Build Project
        run: npm run build

      - name: Dot env
        run: cp config/.production.env ./dist/.env

      # - name: Deploy to Firebase
      #   uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy --force
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #     PROJECT_ID: production

      - name: Publish release
        run: npx release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase develop
        run: |
          git reset --hard
          git checkout develop
          git pull --rebase origin main
          git push
